# Generated by Django 4.2.3 on 2023-07-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0003_estrenos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estrenos',
            name='fecha',
            field=models.CharField(max_length=100),
        ),
    ]
