# Generated by Django 4.2.3 on 2023-07-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0004_alter_estrenos_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='cod_peli',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='cod_serie',
        ),
        migrations.AddField(
            model_name='categoria',
            name='peliculas',
            field=models.ManyToManyField(to='pelis.pelicula'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='series',
            field=models.ManyToManyField(to='pelis.serie'),
        ),
    ]
