# Generated by Django 4.2.3 on 2023-07-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0005_remove_categoria_cod_peli_remove_categoria_cod_serie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estrenos',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serie',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
