# Generated by Django 5.0.1 on 2024-01-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0006_alter_categoria_codigo_alter_estrenos_codigo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='estrenos',
            new_name='Estreno',
        ),
    ]
